services:
  - type: web
    name: rails-backend
    env: ruby
    plan: free
    region: oregon
    buildCommand: bundle install && bundle exec rake assets:precompile db:migrate
    startCommand: bundle exec puma -C config/puma.rb
    envVars:
      - key: RAILS_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: rails-db
          property: connectionString
      - key: SECRET_KEY_BASE
        generateValue: true

databases:
  - name: rails-db
    plan: free
