services:
  - type: web
    name: rails-backend
    env: ruby
    buildCommand: bundle install
    startCommand: bundle exec rails server -b 0.0.0.0 -p 3000
    envVars:
      - key: RAILS_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: rails-db
          property: connectionString
      - key: SECRET_KEY_BASE
        generateValue: true
      - key: RAILS_MASTER_KEY
        fromSecret: RAILS_MASTER_KEY
