services:
  - type: web
    name: rails-backend
    env: ruby
    buildCommand: |
      gem update --system 3.3.22
      bundle install
      bundle exec bootsnap precompile --gemfile
    startCommand: bin/rails server
    envVars:
      - key: RAILS_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
            name: rails-db
            property: connectionString
      - key: SECRET_KEY_BASE
        generateValue: true
      - key: RAILS_MASTER_KEY
        value: your-master-key-here

databases:
  - name: rails-db
